### ISSUE TITLE
Detecting client side disconnect

### ISSUE THREAD

**Issue by johnnyvf24** [itaylor/redux-socket.io#21]
Hello I've been using your redux-socketio connector and I love it, only problem is I have no idea how to detect a disconnect from the client side. Any help is much appreciated. Thanks!

**Comment by itaylor** [comment]
I think the idea with Socket.io is that most of the time, you shouldn't have to worry about that, because with the default config Socket.io is going to automatically retry connecting for you.  That said, if you wanted to put some indicator into your state store that socket.io is not currently connected, you could do something like the below.  It's the super-basic example from readme.md with additional error handling for socket.io connection errors and reconnects:

```js
import { createStore, applyMiddleware } from 'redux';
import createSocketIoMiddleware from 'redux-socket.io';
import io from 'socket.io-client';
let socket = io('http://localhost:3000');
let socketIoMiddleware = createSocketIoMiddleware(socket, "server/");
function reducer(state = {}, action){
  switch(action.type){
    case 'message':
      return { ...state, message:action.data };
    case 'disconnect':
      return { ...state, disconnected: true };
    case 'reconnect': 
      return { ...state, disconnected: false };
    default:
      return state;
  }
}
let store = applyMiddleware(socketIoMiddleware)(createStore)(reducer);
store.subscribe(()=>{
  console.log('new client state', store.getState());
});
store.dispatch({type:'server/hello', data:'Hello!'});
socket.on('connect_timeout', () => store.dispatch({ type: 'disconnect' }));
socket.on('connect_error', () => store.dispatch({ type: 'disconnect' }));
socket.on('reconnect_error', () => store.dispatch({ type: 'disconnect' }));
socket.on('reconnect', () => store.dispatch({ type: 'reconnect' }));
```

There's tons of flexibility built into socket.io for choosing how you configure your reconnection strategy.  I'd suggest reading the socket.io docs on the manager and its events and options:
https://github.com/socketio/socket.io-client/blob/master/docs/API.md#event-connect_error
Perhaps it makes more sense to ratchet down the number of `reconnectionAttempts` and only put something in your state store when you hit that limit.  The needs here probably vary greatly on how tied an app is to constant connectivity to the server side.

**Comment by johnnyvf24** [comment]
Thanks for the info! I appreciate it. This is the part I was missing:

```
socket.on('connect_timeout', () => store.dispatch({ type: 'disconnect' }));
socket.on('connect_error', () => store.dispatch({ type: 'disconnect' }));
socket.on('reconnect_error', () => store.dispatch({ type: 'disconnect' }));
socket.on('reconnect', () => store.dispatch({ type: 'reconnect' }));
```
