### ISSUE TITLE
server reboot, socket is expired. real time is broken

### ISSUE THREAD

**Issue by marcmoo** [itaylor/redux-socket.io#40]
Hi, this awesome kit make my realtime chat and chatlist realtime update possible.
however, when the server get rebooted. the users must get connected again to keep the real time chatlist updated. otherwise, the realtime go broken.
how can I solve this problem?
Thank you

**Comment by itaylor** [comment]
I don't know the specifics of your use case or application, so the best I can do is to give you some generic advice.

Socket.io has many settings on how it attempts to reconnect.   If you need the client to be aggressive in reconnecting, you may want to alter the socket.io options for reconnection retries and make it try more frequently.
https://socket.io/docs/client-api/#new-Manager-url-options

Another thing you might look into is handling the socket.io `reconnect` event and using that to dispatch an action that will make a request to your server that requests recent messages that the client may have missed from the server while the connection was down.
https://socket.io/docs/client-api/#Event-%E2%80%98reconnect%E2%80%99  

If you have only a single server, that is a single point of failure in your system and there likely nothing you can do that will make an application that is truly realtime be available during an outage if your single server is down.  You might instead want to look at having multiple backend servers, perhaps in different datacenters or regions, and have them be able to broadcast socket.io response messages to each other.   One common way to do this is to use something like `socket.io-redis` to back the socket.io messaging with Redis pub/sub so that when one of your node.js socket.io servers goes down, the clients automatically reconnect to another server that is still up and the messages continue to flow.
